# 07A: Working with NumPy



In [1]:
import numpy as np

## Creating and manipulating arrays

In [2]:
# creating numpy arrays (additional not shown in tutorial)
my_list = [1,2,3,4,5,6,7,8,9]  # standard Python list

my_array = np.array([1,2,3,4,5,6,7,8,9])     # creating a NumPy array
my_array = np.array(my_list)                 # creating from an existing list

print(my_list)
print(my_array)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]


In [3]:
# can't mix types with a NumPy array (additional not shown in tutorial)
my_list = ["a", "b", 1, 2]
print(my_list)

my_array = np.array(my_list)   # will show mixed types - text strings and numbers
print(my_array)                # will show singl etype - text strings

['a', 'b', 1, 2]
['a' 'b' '1' '2']


In [4]:
# can specify and change the data type of a NumPy array (additional, not shown in tutorial)
my_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype='f')   # create array as type float
print(my_array)

new_array = my_array.astype('i')   # change to type integer
print(new_array)

[1.1 2.2 3.3 4.4 5.5]
[1 2 3 4 5]


In [5]:
# the shape of an array
my_array = np.array([[1,3,5,7],[2,4,6,8]])
print(my_array.shape)   # .shape is a property of the class for np arrays

(2, 4)


In [7]:
# reshaping an array
new_array = my_array.reshape(1,8)
print(new_array.shape)

(1, 8)


In [8]:
# Transposing an array
my_array = np.array([[1,3,5,7],[2,4,6,8]])

new_array = my_array.T
print(new_array.shape)

(4, 2)


In [9]:
# flattening using flatten()

# only works with arrays. Will not work if split an array in to a list of arrays
new_array = my_array.ravel()
print(new_array)

[1 3 5 7 2 4 6 8]


In [10]:
# flattening using ravel()

# also applies to a list of arrays, hence use this rather than flatten()
new_array = my_array.ravel()
print(new_array)

[1 3 5 7 2 4 6 8]


In [12]:
# splitting up an array
split_one = np.split(new_array,2)  # split the array into 2 (must be divisor)
print(split_one)

split_two = np.split(new_array,[2,6])
print(split_two)

print("")  # extracting each array from the list
print(split_one[0])
print(split_one[1])

[array([1, 3, 5, 7]), array([2, 4, 6, 8])]
[array([1, 3]), array([5, 7, 2, 4]), array([6, 8])]

[1 3 5 7]
[2 4 6 8]


In [13]:
# joining two arrays using concatenate
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])

new_array = np.concatenate((array1,array2))   # join along columns (default, axis=0)
print(new_array)

[1 2 3 4 5 6 7 8]


In [14]:
# sorting an array (additional not shown in tutorial)

# default simple sort is ascending
my_array = np.array([8,3,5,6,7,4,2,1])
my_array.sort()   
print(my_array)

my_array = np.array([[7,8,2,4],[1,6,5,3]])
print(my_array)

# default 2D sort is within array (element-wise)
print(np.sort(my_array))

# sorting a 2D array by row
print(np.sort(my_array, axis=1))

# sorting a 2D array by column
print(np.sort(my_array, axis=0))


[1 2 3 4 5 6 7 8]
[[7 8 2 4]
 [1 6 5 3]]
[[2 4 7 8]
 [1 3 5 6]]
[[2 4 7 8]
 [1 3 5 6]]
[[1 6 2 3]
 [7 8 5 4]]


In [15]:
# searching an array

# using where()
my_array = np.array([1,2,7,2,4,8,9,2,4])
x = np.where(my_array==2)
print(x)

# using searchsorted() - array must be sorted first!
sorted_array = np.sort(my_array)
x = np.searchsorted(sorted_array,2,side='left')   # will return the index position where the specified value should be inserted to maintain sort order
print(x)

(array([1, 3, 7]),)
1


In [16]:
# filtering an array
filter_array = my_array > 4

new_array = my_array[filter_array]
print(new_array)

[7 8 9]


In [17]:
# deep vs. shallow copy
a = np.array([1,2,3])

b = a.view()    # shallow

c = a.copy()    # deep